from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.enums import TA_CENTER

from reportlab.lib import colors

from reportlab.lib.units import inch

from datetime import datetime


def generate_report(results, final_score):

    pdf_path = "Interview_Report.pdf"

    doc = SimpleDocTemplate(

        pdf_path,

        rightMargin=35,

        leftMargin=35,

        topMargin=35,

        bottomMargin=35

    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]

    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    story = []

    # ==========================================
    # TITLE
    # ==========================================

    story.append(

        Paragraph(

            "🤖 AI INTERVIEW BOOTH",

            title_style

        )

    )

    story.append(

        Paragraph(

            "<b>AI Powered Interview Assessment Report</b>",

            heading

        )

    )

    story.append(

        Spacer(1,0.3*inch)

    )

    story.append(

        Paragraph(

            "<b>Report Generated :</b> "

            + datetime.now().strftime("%d %B %Y  %I:%M %p"),

            normal

        )

    )

    story.append(

        Spacer(1,0.3*inch)

    )

    # ==========================================
    # OVERALL SUMMARY
    # ==========================================

    story.append(

        Paragraph(

            "<b>Overall Summary</b>",

            heading

        )

    )

    summary_data = [

        [

            "Metric",

            "Value"

        ],

        [

            "Final Score",

            f"{final_score:.2f}"

        ],

        [

            "Questions Attempted",

            str(len(results))

        ]

    ]

    table = Table(

        summary_data,

        colWidths=[3*inch,2*inch]

    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#2563EB")),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

            ("ALIGN",(0,0),(-1,-1),"CENTER"),

            ("BOTTOMPADDING",(0,0),(-1,0),10),

        ])

    )

    story.append(table)

    story.append(

        Spacer(1,0.4*inch)

    )
        # ==========================================
    # PERFORMANCE SUMMARY
    # ==========================================

    story.append(
        Paragraph(
            "<b>Performance Summary</b>",
            heading
        )
    )

    if final_score >= 85:

        remark = (
            "Excellent performance. The candidate demonstrated strong "
            "technical knowledge, communication skills, and confidence."
        )

    elif final_score >= 70:

        remark = (
            "Good performance. The candidate has a solid understanding "
            "of the concepts with scope for improvement in a few areas."
        )

    elif final_score >= 50:

        remark = (
            "Average performance. Additional practice and revision "
            "are recommended before appearing for interviews."
        )

    else:

        remark = (
            "The candidate needs significant improvement in technical "
            "knowledge and communication skills."
        )

    story.append(
        Paragraph(
            remark,
            normal
        )
    )

    story.append(
        Spacer(1, 0.3 * inch)
    )

    # ==========================================
    # THANK YOU
    # ==========================================

    story.append(
        Paragraph(
            "<b>Thank You!</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            "This report was automatically generated by the "
            "<b>AI Interview Booth</b>. "
            "The evaluation combines technical assessment, "
            "voice confidence, emotion analysis, and stress analysis "
            "to provide an overall interview performance summary.",
            normal
        )
    )

    story.append(
        Spacer(1, 0.2 * inch)
    )

    story.append(
        Paragraph(
            "<font color='grey'><i>"
            "Generated using AI Interview Booth v2.0"
            "</i></font>",
            normal
        )
    )

    # ==========================================
    # BUILD PDF
    # ==========================================

    doc.build(story)

    return pdf_path